"""Shapes used to derive complexipy 8.0.1's cognitive-complexity rules. Run with the pinned venv."""
import complexipy
shapes = {
 "if": "def f(a):\n    if a:\n        pass\n",
 "if_else": "def f(a):\n    if a:\n        pass\n    else:\n        pass\n",
 "if_elif": "def f(a,b):\n    if a:\n        pass\n    elif b:\n        pass\n",
 "if_elif_else": "def f(a,b):\n    if a:\n        pass\n    elif b:\n        pass\n    else:\n        pass\n",
 "elif4": "def f(a):\n    if a==1:\n        pass\n    elif a==2:\n        pass\n    elif a==3:\n        pass\n    elif a==4:\n        pass\n",
 "nested_if": "def f(a,b):\n    if a:\n        if b:\n            pass\n",
 "if_in_elif": "def f(a,b,c):\n    if a:\n        pass\n    elif b:\n        if c:\n            pass\n",
 "if_in_else": "def f(a,b):\n    if a:\n        pass\n    else:\n        if b:\n            pass\n",
 "for": "def f(a):\n    for x in a:\n        pass\n",
 "for_else": "def f(a):\n    for x in a:\n        pass\n    else:\n        pass\n",
 "while": "def f(a):\n    while a:\n        pass\n",
 "while_else": "def f(a):\n    while a:\n        pass\n    else:\n        pass\n",
 "for_if": "def f(a):\n    for x in a:\n        if x:\n            pass\n",
 "try_except": "def f():\n    try:\n        pass\n    except E:\n        pass\n",
 "try_2except": "def f():\n    try:\n        pass\n    except E:\n        pass\n    except F:\n        pass\n",
 "try_finally": "def f():\n    try:\n        pass\n    finally:\n        pass\n",
 "try_else": "def f():\n    try:\n        pass\n    except E:\n        pass\n    else:\n        pass\n",
 "if_in_try": "def f(a):\n    try:\n        if a:\n            pass\n    except E:\n        pass\n",
 "if_in_except": "def f(a):\n    try:\n        pass\n    except E:\n        if a:\n            pass\n",
 "with": "def f():\n    with a:\n        pass\n",
 "if_in_with": "def f(a):\n    with a:\n        if a:\n            pass\n",
 "ternary": "def f(a):\n    return 1 if a else 2\n",
 "ternary_in_if": "def f(a,b):\n    if a:\n        return 1 if b else 2\n",
 "and": "def f(a,b):\n    return a and b\n",
 "and3": "def f(a,b,c):\n    return a and b and c\n",
 "and_or": "def f(a,b,c):\n    return a and b or c\n",
 "and_or_and": "def f(a,b,c,d):\n    return a and b or c and d\n",
 "not_and": "def f(a,b):\n    return not (a and b)\n",
 "if_and": "def f(a,b):\n    if a and b:\n        pass\n",
 "listcomp": "def f(a):\n    return [x for x in a]\n",
 "listcomp_if": "def f(a):\n    return [x for x in a if x]\n",
 "listcomp_2if": "def f(a):\n    return [x for x in a if x if x > 1]\n",
 "listcomp_2for": "def f(a):\n    return [y for x in a for y in x]\n",
 "genexp_if": "def f(a):\n    return sum(x for x in a if x)\n",
 "listcomp_in_if": "def f(a):\n    if a:\n        return [x for x in a if x]\n",
 "match2": "def f(a):\n    match a:\n        case 1:\n            pass\n        case 2:\n            pass\n",
 "if_in_case": "def f(a,b):\n    match a:\n        case 1:\n            if b:\n                pass\n",
 "break": "def f(a):\n    for x in a:\n        break\n",
 "continue": "def f(a):\n    for x in a:\n        continue\n",
 "raise": "def f(a):\n    if a:\n        raise E\n",
 "return_in_if": "def f(a):\n    if a:\n        return 1\n",
 "nested_def": "def f(a):\n    def g():\n        if a:\n            pass\n    return g\n",
 "nested_def_in_if": "def f(a):\n    if a:\n        def g():\n            if a:\n                pass\n",
 "lambda": "def f(a):\n    return lambda x: x\n",
 "lambda_ternary": "def f(a):\n    return lambda x: 1 if x else 2\n",
 "recursion": "def f(a):\n    return f(a-1)\n",
 "assert": "def f(a):\n    assert a\n",
 "walrus_if": "def f(a):\n    if (n := a):\n        pass\n",
 "async_for": "async def f(a):\n    async for x in a:\n        pass\n",
 "deep": "def f(a):\n    for x in a:\n        while x:\n            if x:\n                try:\n                    pass\n                except E:\n                    if a:\n                        pass\n",
}
shapes_shapes2 = {
 "comp_if_n2": "def f(a,b):\n    if a:\n        if b:\n            return [x for x in a if x]\n",
 "comp_n2_noif": "def f(a,b):\n    if a:\n        if b:\n            return [x for x in a]\n",
 "comp_2for_n1": "def f(a):\n    if a:\n        return [y for x in a for y in x]\n",
 "comp_in_comp": "def f(a):\n    return [[y for y in x] for x in a]\n",
 "dictcomp_if": "def f(a):\n    return {x: 1 for x in a if x}\n",
 "setcomp": "def f(a):\n    return {x for x in a}\n",
 "and_in_nested_if": "def f(a,b,c):\n    if a:\n        if b and c:\n            pass\n",
 "ternary_nested": "def f(a,b):\n    return 1 if a else (2 if b else 3)\n",
 "except_in_if": "def f(a):\n    if a:\n        try:\n            pass\n        except E:\n            pass\n",
 "try_in_if_2exc": "def f(a):\n    if a:\n        try:\n            pass\n        except E:\n            pass\n        except F:\n            pass\n",
 "finally_if": "def f(a):\n    try:\n        pass\n    finally:\n        if a:\n            pass\n",
 "tryelse_if": "def f(a):\n    try:\n        pass\n    except E:\n        pass\n    else:\n        if a:\n            pass\n",
 "for_else_if": "def f(a):\n    for x in a:\n        pass\n    else:\n        if a:\n            pass\n",
 "while_in_else": "def f(a):\n    if a:\n        pass\n    else:\n        while a:\n            pass\n",
 "elif_nested": "def f(a,b,c):\n    if a:\n        if b:\n            pass\n        elif c:\n            pass\n        else:\n            pass\n",
 "match_in_if": "def f(a,b):\n    if a:\n        match b:\n            case 1:\n                pass\n",
 "match_guard": "def f(a):\n    match a:\n        case x if x > 1:\n            pass\n",
 "and_not_and": "def f(a,b,c):\n    return a and not b and c\n",
 "and_paren_or": "def f(a,b,c):\n    return a and (b or c)\n",
 "or_paren_or": "def f(a,b,c):\n    return a or (b or c)\n",
 "two_stmts_and": "def f(a,b,c,d):\n    x = a and b\n    y = c and d\n",
 "lambda_if_n1": "def f(a):\n    if a:\n        return lambda x: 1 if x else 2\n",
 "lambda_and": "def f(a):\n    return lambda x: x and a\n",
 "recursion2": "def f(a):\n    if a:\n        return f(a-1) + f(a-2)\n",
 "method_recur": "class C:\n    def m(self, a):\n        return self.m(a)\n",
 "method": "class C:\n    def m(self, a):\n        if a:\n            pass\n",
 "nested_class": "def f(a):\n    class K:\n        def g(self):\n            if a:\n                pass\n    return K\n",
 "ternary_in_comp": "def f(a):\n    return [1 if x else 2 for x in a]\n",
 "for_in_while_break": "def f(a):\n    while a:\n        for x in a:\n            if x:\n                break\n",
 "if_comp_cond": "def f(a):\n    if any(x for x in a):\n        pass\n",
 "with_in_for": "def f(a):\n    for x in a:\n        with x:\n            if x:\n                pass\n",
 "async_with": "async def f(a):\n    async with a:\n        if a:\n            pass\n",
 "decorated": "@dec\ndef f(a):\n    if a:\n        pass\n",
 "empty": "def f():\n    pass\n",
 "module_level": "if a:\n    pass\ndef f():\n    pass\n",
}
shapes_shapes3 = {
 "comp_in_call": "def f(a):\n    g([x for x in a])\n",
 "comp_in_call_ret": "def f(a):\n    return g([x for x in a])\n",
 "comp_assign": "def f(a):\n    y = [x for x in a]\n",
 "comp_in_dict": "def f(a):\n    return {'k': [x for x in a]}\n",
 "ternary_in_call": "def f(a):\n    g(1 if a else 2)\n",
 "ternary_kw": "def f(a):\n    g(x=1 if a else 2)\n",
 "ternary_assign": "def f(a):\n    y = 1 if a else 2\n",
 "ternary_ret_call": "def f(a):\n    return g(1 if a else 2)\n",
 "and_in_call": "def f(a,b):\n    g(a and b)\n",
 "lambda_in_call": "def f(a):\n    g(lambda x: 1 if x else 2)\n",
 "for_in_try": "def f(a):\n    try:\n        for x in a:\n            pass\n    except E:\n        pass\n",
 "for_in_try_noexc": "def f(a):\n    try:\n        for x in a:\n            pass\n    finally:\n        pass\n",
 "if_in_try_noexc": "def f(a):\n    try:\n        if a:\n            pass\n    finally:\n        pass\n",
 "while_in_try": "def f(a):\n    try:\n        while a:\n            pass\n    except E:\n        pass\n",
 "for_call_iter": "def f(a):\n    for x in g(a):\n        pass\n",
 "if_call_cond": "def f(a):\n    if g(a):\n        pass\n",
 "if_in_call_lambda": "def f(a):\n    return sorted(a, key=lambda x: x if x else 0)\n",
 "await_call_comp": "async def f(a):\n    await g([x for x in a])\n",
 "method_call_comp": "def f(a):\n    self.g([x for x in a])\n",
 "expr_stmt_comp": "def f(a):\n    [x for x in a]\n",
 "call_ret_ternary_attr": "def f(a):\n    return a.g(1 if a else 2)\n",
}
shapes_shapes4 = {
 "nd_noparam": "def f(a):\n    def g():\n        if a:\n            pass\n",
 "nd_param": "def f(a):\n    def g(x):\n        if x:\n            pass\n",
 "nd_param_ret": "def f(a):\n    def g(x):\n        if x:\n            pass\n    return g\n",
 "nd_noparam_ret": "def f(a):\n    def g():\n        if a:\n            pass\n    return g\n",
 "nd_after_stmt": "def f(a):\n    y = 1\n    def g():\n        if a:\n            pass\n",
 "nd_two_ifs": "def f(a):\n    def g():\n        if a:\n            if a:\n                pass\n",
 "nd_async_comp": "def f(a):\n    async def g(u):\n        return [x for x in u]\n",
 "nd_comp": "def f(a):\n    def g(u):\n        return [x for x in u]\n",
 "nd_comp_noparam": "def f(a):\n    def g():\n        return [x for x in a]\n",
 "nd2": "def f(a):\n    def g():\n        def h():\n            if a:\n                pass\n",
}
shapes_shapes5 = {
 "def_in_for":        ("def f(a):\n    for x in a:\n        def g():\n            if x:\n                pass\n", "for1 + if(1+depth1)=2 -> 3"),
 "def_in_for_if":     ("def f(a):\n    for x in a:\n        if x:\n            def g():\n                if x:\n                    pass\n", "for1 if2 + inner(1+1)=2 -> 5"),
 "deco_docstring":    ("def f(fn):\n    \"\"\"doc\"\"\"\n    def g(*a):\n        if a:\n            pass\n    return g\n", "decorator w/ docstring"),
 "deco_wraps":        ("def f(fn):\n    @wraps(fn)\n    def g(*a):\n        if a:\n            pass\n    return g\n", "decorated inner"),
 "deco_two_defs":     ("def f(fn):\n    def g():\n        if fn:\n            pass\n    def h():\n        pass\n    return g\n", "two defs + return"),
 "return_other":      ("def f(fn):\n    def g():\n        if fn:\n            pass\n    return fn\n", "return other name"),
 "lambda_in_def":     ("def f(a):\n    def g():\n        return lambda x: 1 if x else 2\n", "g depth1, lambda +1 -> ternary 1+2"),
 "if_in_nested_if":   ("def f(a):\n    def g():\n        if a:\n            if a:\n                pass\n        else:\n            pass\n", "g: if2 if3 else1 -> 6"),
 "method_nested_def": ("class C:\n    def m(self):\n        def g():\n            if self:\n                pass\n", "method nested def"),
 "async_nested":      ("async def f(a):\n    async def g():\n        if a:\n            pass\n", "async nested"),
}
shapes_shapes6 = {
 "and_genexp":       "def f(a):\n    return a and all(x for x in a)\n",
 "genexp_only":      "def f(a):\n    return all(x for x in a)\n",
 "and_call_list":    "def f(a):\n    return a and all([x for x in a])\n",
 "and_listcomp":     "def f(a):\n    return a and [x for x in a]\n",
 "or_genexp":        "def f(a):\n    return a or all(x for x in a)\n",
 "genexp_in_assign": "def f(a):\n    y = a and any(x for x in a)\n",
 "comp_in_binop":    "def f(a):\n    return sum(x for x in a) - 1\n",
 "comp_in_list":     "def f(a):\n    return [sum(x for x in a)]\n",
 "comp_in_dictval":  "def f(a):\n    return {'k': sum(x for x in a)}\n",
 "comp_in_spread":   "def f(a):\n    return {**a, 'k': [x for x in a]}\n",
 "listcomp_nested_dict": "def f(a):\n    return [{'k': sum(y for y in x)} for x in a]\n",
}
shapes_shapes7 = {
 "ternary_in_and":   "def f(a,b):\n    return a and (1 if b else 2)\n",
 "ternary_in_binop": "def f(a,b):\n    return a + (1 if b else 2)\n",
 "and_in_binop":     "def f(a,b):\n    return 1 + (a and b)\n",
 "binop_in_ternary": "def f(a,b):\n    return (a + b) if a else 0\n",
 "comp_in_compare":  "def f(a):\n    return len([x for x in a]) > 1\n",
 "comp_in_not":      "def f(a):\n    return not any(x for x in a)\n",
 "comp_in_unary":    "def f(a):\n    return -sum(x for x in a)\n",
 "comp_in_subscript":"def f(a):\n    return a[[x for x in a][0]]\n",
 "comp_in_attr_call":"def f(a):\n    return ','.join(x for x in a)\n",
 "and_in_compare":   "def f(a,b):\n    return (a and b) == 1\n",
 "or_in_and_paren":  "def f(a,b,c):\n    return a and (b or c)\n",
 "if_cond_comp_and": "def f(a):\n    if a and any(x for x in a):\n        pass\n",
}
shapes_shapes9 = {
 "(a or b) and c":        "def f(a,b,c):\n    return (a or b) and c\n",
 "(a or b) and not c":    "def f(a,b,c):\n    return (a or b) and not c\n",
 "a and (b or c)":        "def f(a,b,c):\n    return a and (b or c)\n",
 "not c and (a or b)":    "def f(a,b,c):\n    return not c and (a or b)\n",
 "c and not (a or b)":    "def f(a,b,c):\n    return c and not (a or b)\n",
 "not (a or b)":          "def f(a,b):\n    return not (a or b)\n",
 "(a and b) or c":        "def f(a,b,c):\n    return (a and b) or c\n",
 "a or (b and c)":        "def f(a,b,c):\n    return a or (b and c)\n",
 "(a or b) and (c or d)": "def f(a,b,c,d):\n    return (a or b) and (c or d)\n",
 "a and b and (c or d)":  "def f(a,b,c,d):\n    return a and b and (c or d)\n",
 "(a or b) and c and d":  "def f(a,b,c,d):\n    return (a or b) and c and d\n",
 "x and not y":           "def f(x,y):\n    return x and not y\n",
 "not x and y":           "def f(x,y):\n    return not x and y\n",
}

for table in [v for k, v in dict(globals()).items() if k.startswith("shapes")]:
    for name, src in table.items():
        src = src[0] if isinstance(src, tuple) else src
        print(f"{name:24} {[fn.complexity for fn in complexipy.code_complexity(src).functions]}")
