/**
 * Run every tool over the hand-written fixtures in `fixtures/` and tabulate the
 * result, so each divergence mechanism claimed in findings.md can be checked in
 * isolation instead of being inferred from corpus aggregates.
 *
 * Each fixture function isolates ONE counting-convention difference.
 *
 * Usage: node probe_fixtures.mjs <fixturesDir> <oursReport.json> <baselines.json>
 *                                <diagnostics.json> <out.md>
 */

import fs from 'node:fs';

const [fixturesDir, oursPath, basePath, diagPath, outPath] = process.argv.slice(2);

const ours = JSON.parse(fs.readFileSync(oursPath, 'utf8'));
const base = JSON.parse(fs.readFileSync(basePath, 'utf8'));
const diag = JSON.parse(fs.readFileSync(diagPath, 'utf8')).counts;

const oursByKey = new Map();
for (const pf of ours.perFile ?? []) {
  for (const fn of pf.functionMetrics ?? []) oursByKey.set(`${pf.file}:${fn.startLine}`, fn);
}
const key = (r) => `${r.file}:${r.line}`;
const tsc = new Map(base.tsComplex.map((r) => [key(r), r.value]));
const sonar = new Map(base.sonar.map((r) => [key(r), r.value]));
const esc = new Map(base.escomplexRaw.map((r) => [key(r), r.value]));

const rows = [];
for (const inv of base.inventory.sort((a, b) =>
  a.file.localeCompare(b.file) || a.line - b.line)) {
  const k = `${inv.file}:${inv.line}`;
  const o = oursByKey.get(k);
  const d = diag[k] ?? {};
  const constructs = Object.entries(d)
    .filter(([, v]) => v)
    .map(([n, v]) => `${n}=${v}`)
    .join(', ');
  rows.push({
    fn: `${inv.file}:${inv.line} ${inv.name ?? '@anon'}`,
    cycOurs: o ? o.cyclomaticComplexity : null,
    cycTsc: tsc.has(k) ? tsc.get(k) : null,
    cogOurs: o ? o.cognitiveComplexity : null,
    // sonarjs reports only above-threshold functions; absence at threshold 0
    // means a score of exactly 0.
    cogSonar: sonar.has(k) ? sonar.get(k) : 0,
    volOurs: o ? o.halstead.volume : null,
    volEsc: esc.has(k) ? Number(esc.get(k).toFixed(1)) : null,
    constructs,
  });
}

const cell = (v) => (v === null ? '_absent_' : String(v));
const mark = (a, b) => (a === null || b === null ? '' : a === b ? '' : ' ⚠');

let md = '<!-- generated by probe_fixtures.mjs; do not edit by hand -->\n\n';
md += '| fixture function | cyc ours | cyc ts-complex | cog ours | cog sonarjs | ';
md += 'vol ours | vol escomplex | constructs present |\n';
md += '|---|---|---|---|---|---|---|---|\n';
for (const r of rows) {
  md += `| \`${r.fn}\` | ${cell(r.cycOurs)}${mark(r.cycOurs, r.cycTsc)} | ${cell(r.cycTsc)} | `;
  md += `${cell(r.cogOurs)}${mark(r.cogOurs, r.cogSonar)} | ${cell(r.cogSonar)} | `;
  md += `${cell(r.volOurs)} | ${cell(r.volEsc)} | ${r.constructs || '—'} |\n`;
}
md += '\n⚠ marks a disagreement with the corresponding baseline.\n';

fs.writeFileSync(outPath, md);
console.error(`    [fixtures] ${rows.length} functions tabulated from ${fixturesDir}`);
